# Generated by rust2rpm 27
%bcond check 1

%global crate cargo-rpmstatus

Name:           rust-cargo-rpmstatus
Version:        0.2.2
Release:        %autorelease
Summary:        Cargo-tree for RPM packaging

License:        (MIT OR Apache-2.0) AND GPL-3.0-or-later
URL:            https://crates.io/crates/cargo-rpmstatus
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          cargo-rpmstatus-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24
Requires:       cargo
Requires:       rust

%global _description %{expand:
Cargo-tree for RPM packaging.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

# (MIT OR Apache-2.0) AND Unicode-DFS-2016 # [1]
# 0BSD OR MIT OR Apache-2.0
# Apache-2.0 OR BSL-1.0
# Apache-2.0 OR ISC OR MIT
# Apache-2.0 OR MIT # [2] (dup 1)
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# BSD-2-Clause OR Apache-2.0 OR MIT
# BSD-3-Clause
# GPL-3.0
# ISC
# ISC AND MIT AND OpenSSL
# MIT
# MIT OR Apache-2.0 # (dup 1,2)
# MIT OR Apache-2.0 OR Zlib # [3]
# MIT OR Zlib OR Apache-2.0 # (dup 3!)
# MPL-2.0
# Unlicense OR MIT
# Zlib OR Apache-2.0 OR MIT # (dup 3!)
License:       (MIT OR Apache-2.0) AND Unicode-DFS-2016 AND (0BSD OR MIT OR Apache-2.0) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR ISC OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND BSD-3-Clause AND GPL-3.0 AND ISC AND MIT AND OpenSSL AND (MIT OR Apache-2.0 OR Zlib) AND MPL-2.0 AND (Unlicense OR MIT)


# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-Apache-2.0
%license LICENSE-GPL-3.0-or-later
%license LICENSE-MIT
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/cargo-rpmstatus

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%if %{with check_online}
  %cargo_test
%else
  %cargo_test is_
%endif
%endif

%changelog
%autochangelog
