[tests]
skip=["db::tests::online_check_version_reqs"]
comments=["Skip online tests, online_check_version_reqs needs connectivity. Not working in mock."]

[requires]
bin=["rust", "cargo"]

[package]
extra-files=["%doc %{_mandir}/man1/%{crate}.1*"]

[scripts]
install.post=[
	"# setup man page",
	"mkdir -p %{buildroot}%{_mandir}/man1",
	"install -p -m 0644 %{crate}.1 %{buildroot}%{_mandir}/man1",
]
