# Generated by rust2rpm 26
%bcond_without check

%global crate cargo-rpmstatus

Name:           rust-cargo-rpmstatus
Version:        0.2.0
Release:        %autorelease
Summary:        Cargo-tree for RPM packaging

License:        GPL-3.0
URL:            https://crates.io/crates/cargo-rpmstatus
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          cargo-rpmstatus-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Cargo-tree for RPM packaging.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/cargo-rpmstatus

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
